### ISSUE TITLE
Insecure code

### ISSUE THREAD

**Issue by Mizaro** [Gabisonfire/torrentio-scraper-sh#9]
I set up the code using docker-compose on a machine in a cloud VM and a virus named `kdevtmpfsi` got a way to install itself on my VM. 
Any idea what should be changed?

**Comment by davidjameshowell** [comment]
It sounds more likely that you had a misconfiguration with your Cloud VM, either due to weak passwords or not using key-based authentication to the server that caused someone to gain root access to your machine. 

See simple removal steps here: https://www.brycematheson.io/how-to-permanently-kill-and-remove-kdevtmpfsi-kinsing/

**Comment by Gabisonfire** [comment]
Yeah nothing in this code was modifiedbeside the docker compose file. Make sure your server is properly secured.
